title: "Then Some"
working-title: "<span class='first'>T</span>hen <span class='first'>S</span>ome"
email: 

permalink:  /:categories/:title/
description: > 
  A Theme for which I have high hopes
baseurl: "" 
url: "http://ir.ez.lv"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
