title: "Black Izris"
working-title: "<span class='first'>B</span>lack <span class='first'>I</span>zris"
email: 

permalink:  /:categories/:title/
description: > 
  A Theme for which I have high hopes
baseurl: "" 
url: "http://this.ez.lv"

markdown: kramdown
